version: '2'

services:
  moodpack:
    image: edymoo/minecraft:moodpack
    container_name: mc-moodpack
    tty: true
    ports:
     - '25565:25565'
    environment:
     - RAM_XMS=512M
     - RAM_XMX=3G
     - MC_MAX_PLAYERS=20
     - MC_PORT=25565
     - MC_VIEW_DISTANCE=6
     - MC_SPAWN_PROTECTION=0
     - MC_ALLOW_NETHER=false
     - MC_DIFFICULTY=1
     - MC_SPAWN_MONSTERS=true
     - MC_SPAWN_ANIMALS=true
     - MC_ACHIEVEMENTS=false
     - MC_PVP=true
     - MC_ALLOW_FLIGHT=true
     - MC_WHITELIST=false
     - MC_GENERATE_STRUCTURES=true
     - MC_MOTD=Docker Server
    volumes:
     - /srv/minecraft/moodpack/world:/srv/minecraft/moodpack/world
     - /srv/minecraft/moodpack/plugins:/srv/minecraft/moodpack/plugins