version: '2'

services:
  moodpack:
    image: edymoo/minecraft:moodpack
    container_name: mc-moodpack
    tty: true
    ports:
     - '25565:25565'
    environment:
     - MC_MAX_PLAYERS=20
     - MC_PORT=25565
     - MC_VIEW_DISTANCE=3
     - RAM_XMS=512M
     - RAM_XMX=3G
    volumes:
     - /srv/minecraft/moodpack/world:/srv/minecraft/moodpack/world
     - /srv/minecraft/moodpack/plugins:/srv/minecraft/moodpack/plugins